services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-restaurant-management}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata-go-restaurant-management:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-restaurant-management}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - restaurant-management-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin-go-restaurant-management:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - restaurant-management-net

volumes:
  pgdata-go-restaurant-management:
  pgadmin-go-restaurant-management:

networks:
  restaurant-management-net:
    driver: bridge